name: Pipeline

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: pipeline-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    name: Code Formatting
    uses: ./.github/workflows/ci-format.yml

  analysis:
    name: Code Analysis
    needs: format
    uses: ./.github/workflows/ci-analysis.yml
    permissions:
      contents: read
      pull-requests: write
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
